### ISSUE TITLE
Python code missing

### ISSUE THREAD

**Issue by SKM-bio** [AakashSudhakar/biodata-compound-activity-with-bioassays#1]
Hi, 

Great collection and step by step protocol to learn the bioassay activity prediction, but I couldn't find a complete 02-intermediate-data-processing.ipynb and 03-predictive-data-modeling.ipynb notebook. Could you add them here. It would be really useful for my learning. Thanks.

**Comment by djprofessorkash** [comment]
Hi @SKM-bio 

Thanks for checking out this project! I'm unfortunately shelved this particular bioassay investigation and prediction project for now due to professional work and other pressing side projects. 😕

I expect to get back to it in a few months time (ideally by June) to continue the investigation, but cannot say for sure. In the meantime, I urge you to check out the data's source on Kaggle (I believe I linked it somewhere in the repo's docs) and check out some of the other investigations being done. ✅

Thanks for taking the time to check out my project progress so far! 👋

Yours,
Kash
